# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170809_1414'),
        ('operation', '0002_auto_20170813_2147'),
    ]

    operations = [
    ]
