# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=18)),
            ],
        ),
    ]
